### ISSUE TITLE
Order of text blocks (#pab-1,2,3,4,...) vanishes when they are empty

### ISSUE THREAD

**Issue by MarekPro1** [gavalierm/pab-propresenter-arena-bridge#4]
When we have text that we only want to go on stage display but not to stream we fill only stage display block 3, but to pab it sends as block 1 because they are empty so propresenter puts it on front. Can you find some solution to it.
![image](https://github.com/gavalierm/pab-propresenter-arena-bridge/assets/110824876/4d7040cf-a085-44b1-8db3-4038b636a469)
![image](https://github.com/gavalierm/pab-propresenter-arena-bridge/assets/110824876/27ac44d5-2bc8-4852-9d9b-5e1d652126f2)

Even when i put space in it, it does not work.
The problem i think is making propresenter.

**1. solution that can be is**
that we agree on a special character like "&" that you always deletes in pab. and we put it in the empty blocks
![image](https://github.com/gavalierm/pab-propresenter-arena-bridge/assets/110824876/0cfc2f7f-a174-4cbe-aafd-9d4d739aed1d)
but this solution is pretty stupid :)

**Comment by gavalierm** [comment]
I have to check it, because this is a bug for sure. Blocks needs to be specific event if they are empty.

**Comment by gavalierm** [comment]
https://github.com/gavalierm/pab-propresenter-arena-bridge/commit/e572502caf00040687a35cc5973b432d6bca0ebe
